# Generated by Django 5.2.17 on 2026-09-27 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DLPPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('credential', 'Credential'), ('pii', 'Personal data'), ('confidential_data', 'Confidential data'), ('prompt_injection', 'Prompt injection'), ('jailbreak', 'Jailbreak'), ('data_exfiltration', 'Data exfiltration')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('regex_patterns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_identifier_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('ALLOWED', 'ALLOWED'), ('BLOCKED', 'BLOCKED')], max_length=7)),
                ('highest_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('matched_policy_codes', models.JSONField(default=list)),
                ('safe_detection_summary', models.JSONField(default=list)),
                ('latency_ms', models.PositiveIntegerField()),
                ('forwarded_to_llm', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
