"""Additional configurable policies; no workbook-specific prompt allowlists."""
EXTRA_RULES = [
    ('SSN', 'pii', r'(?<!\d)\d{3}[ .-]\d{2}[ .-]\d{4}(?!\d)|\bssn\b\s*[:=]?\s*(?:\d[ .-]*){9}\b'),
    ('INTERNATIONAL_ID', 'pii', r'\b(?:passport(?: number)?|voter id(?: number)?|steuer.id|insee(?: number)?|ein|sin(?: number)?|tfn|resident id|emirates id|biometric enrollment id)\b\s*(?:is|[:=])?\s*[a-z0-9 -]*\d{3,}|\b(?:national insurance number|ni number)\s*[:=]?\s*[a-z]{2}\s*\d{2}\s*\d{2}\s*\d{2}\s*[a-d]\b'),
    ('PAYMENT_IDENTIFIER', 'pii', r'\b(?:upi id|swift(?:/bic)?(?: code)?|bssid(?: address)?|mac address)\s*(?:is|[:=])?\s*[a-z0-9@:.\-]{6,}|\b(?:card(?: number)?|mastercard|visa)\s*(?:is|[:=])?\s*(?:\d[ =.\-]*){13,19}(?!\d)|\b(?:trading|401k) account(?: number)?\s*[:=]?\s*[a-z0-9-]*\d{3,}'),
    ('SECRET_ASSIGNMENT', 'credential', r'\b(?:password|p@ssw0rd|secret key|s3cr3t k3y|client secret|api key|auth token|license key)\b.{0,55}\b(?:is|[:=])\s*\S+|\b(?:api key|auth token|license key)\s+[a-z0-9-]{12,}|authorization\s*:\s*basic\s+[a-z0-9+/=]+|https://hooks\.slack\.com/services/\S+|jdbc:\S+|\bsk-proj-[a-z0-9]{8,}'),
    ('ACTIVE_PAYLOAD', 'prompt_injection', r'<script\b|<[^>]+\bon(?:error|load)\s*=|<!entity\b|(?:\.\.[/\\]){2,}|\$\s*\(\s*(?:curl|wget)|\b(?:cat\s+/etc/(?:passwd|shadow)|rm\s+-rf\b|xp_cmdshell|drop\s+table)|[|;]\s*(?:sh|bash|wget|curl)\b|["\x27]\$(?:ne|gt|where)["\x27]\s*:|\(\|\(uid=|\)\(uid=|\b(?:or\s+1\s*=\s*1|and\s+sleep\s*\(|order\s+by\s+\d+\s*--)'),
    ('CONFIDENTIAL_CONTEXT', 'confidential_data', r'\b(?:confidential|proprietary|unpatented|unfiled|unannounced|unpublished|board.only|internal.only)\b.{0,120}\b(?:report|merger|acquisition|pricing|cap table|algorithm|source|patent|layoff|severance|revenue|equity|arbitration|churn|discount|design|formula)\b|\b(?:our|internal|this|employee|team)\b.{0,55}\b(?:payroll list|salary bands|board meeting|acquisition|cash runway|payment service source|kubernetes deployment|performance improvement plan|stock option allocations)\b|\b(?:patient|prescription note|lab results)\b.{0,100}\b(?:diagnosed|metformin|refill|positive|mrn|icd|diabetes)\b'),
    ('INJECTION_INTENT', 'prompt_injection', r'\b(?:ignore|disregard|forget)\b.{0,50}\b(?:your rules|company policy|moderation|translation task|dlp|previous context)\b|\b(?:disable|override)\b.{0,35}\b(?:pii|dlp|logging|security rules)\b|\b(?:you are now dan|unfiltered (?:ai|assistant)|no restrictions now|system override)\b|\b(?:repeat|summarize|list|reveal|output|show|print)\b.{0,60}\b(?:system prompt|all instructions above|api credentials|sensitive environment variables|hidden configuration)\b|\b(?:jailbreak prompt)\b.{0,50}\bexecute\b'),
    ('EXTERNAL_PAYLOAD', 'data_exfiltration', r'document\.cookie|https?://\S+[?&](?:data|key|card|token|cookie)=\S+|\b(?:link|image|url|markdown)\b.{0,100}\b(?:input history|secret keys|token payload)\b'),
]
